[package]
name = "netd"
version.workspace = true
license-file.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true

[dependencies]
libc_string = { workspace = true }
nanvix-net = { workspace = true }
nvx = { workspace = true }
sys = { workspace = true }
syslog = { workspace = true }

[features]
# Logging Features
trace = ["debug"]
debug = ["info"]
info = ["warn"]
warn = ["error"]
error = ["panic"]
panic = []

[lints]
workspace = true
