[package]
name = "netd"
version.workspace = true
license-file.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true

[dependencies]
libc_string = { workspace = true }
nvx = { workspace = true }
sys = { workspace = true }
syscall = { workspace = true, features = ["syscall"] }
syslog = { workspace = true }
smoltcp = { workspace = true, features = ["medium-ethernet", "socket-udp", "socket-icmp"] }

[features]
# Logging Features
trace = ["nvx/trace", "syslog/trace"]
debug = ["nvx/debug", "syslog/debug"]
info = ["nvx/info", "syslog/info"]
warn = ["nvx/warn", "syslog/warn"]
error = ["nvx/error", "syslog/error"]
panic = ["nvx/panic", "syslog/panic"]

[build-dependencies]
cc = { workspace = true }
cfg-if = { workspace = true }

[lints]
workspace = true
