[package]
name = "nanvix-net"
version.workspace = true
license-file.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[lib]
crate-type = ["lib"]

[features]
default = []
syscall-time = ["dep:syscall"]
# Logging Features
trace = ["nvx/trace", "syslog/trace"]
debug = ["nvx/debug", "syslog/debug"]
info = ["nvx/info", "syslog/info"]
warn = ["nvx/warn", "syslog/warn"]
error = ["nvx/error", "syslog/error"]
panic = ["nvx/panic", "syslog/panic"]

[dependencies]
nvx = { workspace = true }
smoltcp = { workspace = true, features = ["medium-ethernet"] }
syscall = { workspace = true, optional = true, features = ["syscall"] }
sys = { workspace = true }
syslog = { workspace = true }
volatile = { workspace = true }

[lints]
workspace = true
